spring:
  datasource:
    url: jdbc:mysql://gumoximall.com:3306/gumoximall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: gumoximall-ware
  cloud:
    nacos:
      discovery:
        server-addr: gumoximall.com:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8009

logging:
  level:
    com.gumoxi.gumoximall: debug
